### ISSUE TITLE
Cron "php /var/www/nextcloud/occ preview:pre-generate"

### ISSUE THREAD

**Issue by tetzlav** [nextcloud/previewgenerator#210]
With Nextcloud 19.0.4 + Preview Generator 2.3.0 + Cron "php /var/www/nextcloud/occ preview:pre-generate" i got:

```
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\GroupFolders\Command\Trashbin\Cleanup::__construct(), 0 passed in /var/www/nextcloud/lib/private/Console/Application.php on line 224 and exactly 3 expected in /var/www/nextcloud/apps/groupfolders/lib/Command/Trashbin/Cleanup.php:49
Stack trace:
#0 /var/www/nextcloud/lib/private/Console/Application.php(224): OCA\GroupFolders\Command\Trashbin\Cleanup->__construct()
#1 /var/www/nextcloud/lib/private/Console/Application.php(136): OC\Console\Application->loadCommandsFromInfoXml()
#2 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands()
#3 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#4 {main}
```
I found https://github.com/nextcloud/groupfolders/issues/1074, but enabling Trashbin does not solve the error.

**Comment by joshtrichards** [comment]
This is a very old issue. Not sure the original cause off-hand, but it would have likely been a GF matter not specific to the `previewgenerator`. Let us know if still experiencing this and can be revisited.
