### ISSUE TITLE
Failed to connect to the database: An exception occurred in driver: SQLSTATE

### ISSUE THREAD

**Issue by benpryde** [nextcloud/previewgenerator#215]
Hi, I received this error while executing this command "sudo -u www-data php -f /var/www/nextcloud/occ preview:generate-all"

NextCloud: 20.0.3
Previewgenerator: 3.1.0
openmediavault on debian 10

I'm new to linux, Not sure if anyone encountered this problem, seems like something related to database. Thank you!

```
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known in /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/DB/Connection.php:72
Stack trace:
#0 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1449): OC\DB\Connection->connect()
#1 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(892): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/DB/Connection.php(202): Doctrine\DBAL\Connection->executeQuery()
#3 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): OC\DB\Connection->executeQuery()
#4 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(217): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/AppConfig.php(345): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/AppConfig.php(110): OC\AppConfig->loadConfigValues()
#7 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/AppConfig.php(301): OC\AppConfig->getApps()
#8 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/legacy/OC_App.php(949): OC\AppConfig->getValues()
#9 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/Server.php(668): OC_App::getAppVersions()
#10 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}()
#11 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet()
#13 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/ServerContainer.php(156): OC\AppFramework\Utility\SimpleContainer->query()
#14 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/Server.php(1677): OC\ServerContainer->query()
#15 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/Server.php(1017): OC\Server->getMemCacheFactory()
#16 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}()
#17 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#18 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet()
#19 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/ServerContainer.php(156): OC\AppFramework\Utility\SimpleContainer->query()
#20 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/Server.php(1977): OC\ServerContainer->query()
#21 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/Files/View.php(118): OC\Server->getLockingProvider()
#22 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/Server.php(395): OC\Files\View->__construct()
#23 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}()
#24 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#25 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet()
#26 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/ServerContainer.php(156): OC\AppFramework\Utility\SimpleContainer->query()
#27 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/private/Server.php(1324): OC\ServerContainer->query()
#28 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/base.php(595): OC\Server->boot()
#29 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/lib/base.php(1091): OC::init()
#30 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/console.php(49): require_once('/srv/dev-disk-b...')
#31 /srv/dev-disk-by-label-Cloud/appdata/nextcloud/config/www/nextcloud/occ(11): require_once('/srv/dev-disk-b...')
#32 {main}root@ExteriorStorage:~# ^C
```

**Comment by sanglyb** [comment]
I also have the same issue. Are their any updates?

**Comment by joshtrichards** [comment]
Hi @benpryde - Yes, this is saying that `occ` was unable to look up the hostname of your database server. This is a configuration issue of some sort.

This is primarily a bug reporting and enhancement request channel. It's used to identify patterns and prioritize bugs and enhancements for development. Each report is read, but since this is not a tech support channel, not every request receives an individual response.

I realize this is old, but in case you experience a similar problem again, I suggest posting at the [Nextcloud Help Forum](https://help.nextcloud.com). That's the place to go for assistance regarding configuration/installation and general troubleshooting.

I'm sorry you never saw a response to this here and I hope you found help in the meantime elsewhere!
