### ISSUE TITLE
Argument #2 ($height) must be greater than 0

### ISSUE THREAD

**Issue by amo13** [nextcloud/previewgenerator#236]
When scanning a folder with a few gif images, the preview generation crashes:
```
An unhandled exception has been thrown:
ValueError: imagecreatetruecolor(): Argument #2 ($height) must be greater than 0 in /usr/share/webapps/nextcloud/lib/private/legacy/OC_Image.php:926
Stack trace:
#0 /usr/share/webapps/nextcloud/lib/private/legacy/OC_Image.php(926): imagecreatetruecolor()
#1 /usr/share/webapps/nextcloud/lib/private/legacy/OC_Image.php(898): OC_Image->preciseResizeNew()
#2 /usr/share/webapps/nextcloud/lib/private/legacy/OC_Image.php(1148): OC_Image->resizeNew()
#3 /usr/share/webapps/nextcloud/lib/private/Preview/Generator.php(429): OC_Image->resizeCopy()
#4 /usr/share/webapps/nextcloud/lib/private/Preview/Generator.php(186): OC\Preview\Generator->generatePreview()
#5 /usr/share/webapps/nextcloud/lib/private/PreviewManager.php(205): OC\Preview\Generator->generatePreviews()
#6 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(203): OC\PreviewManager->generatePreviews()
#7 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(174): OCA\PreviewGenerator\Command\Generate->parseFile()
#8 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#9 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#10 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#11 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#12 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#13 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#14 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#15 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#16 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(155): OCA\PreviewGenerator\Command\Generate->parseFolder()
#17 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(123): OCA\PreviewGenerator\Command\Generate->generateUserPreviews()
#18 /usr/share/webapps/nextcloud/lib/private/User/Manager.php(646): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}()
#19 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(124): OC\User\Manager->callForSeenUsers()
#20 /usr/share/webapps/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute()
#21 /usr/share/webapps/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#22 /usr/share/webapps/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#23 /usr/share/webapps/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#24 /usr/share/webapps/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#25 /usr/share/webapps/nextcloud/console.php(100): OC\Console\Application->run()
#26 /usr/share/webapps/nextcloud/occ(11): require_once('/usr/share/weba...')
```

I wasn't able to figure out if it is possible to generate previews only for some specific folders. I have a lot of files in my user account and the images I'd like to have previews for are only a fraction of all files.

**Comment by OneTwoBarbecue** [comment]
Facing the same problem here. 

NC 21.0.2 running on Ubuntu 20.04

Folders that contain small pictures - e.g. folders with html-data that contain thin lines as graphic files - will cause preview-generation to throw the error shown above. Then preview-generation stops.

It would be nice, if generation could just continue, ignoring the error since no previews need to be generated for this kind of files.

Kind regards, Marco

**Comment by cagelight** [comment]
Came here to report this, unfortunately seems like this repo is largely unmaintained...

**Comment by abondis** [comment]
I seem to have the same issue, I updated yesterday (2022-02-10) to Nextcloud 22.2.3 and have the Photo app v4.0.0
Is there a new version that my instance didn't receive for any reason? 
```
An unhandled exception has been thrown:
ValueError: imagecreatetruecolor(): Argument #2 ($height) must be greater than 0 in /var/www/html/lib/private/legacy/OC_Image.php:933
Stack trace:
#0 /var/www/html/lib/private/legacy/OC_Image.php(933): imagecreatetruecolor(256, 0)
#1 /var/www/html/lib/private/legacy/OC_Image.php(905): OC_Image->preciseResizeNew(256, 0)
#2 /var/www/html/lib/private/legacy/OC_Image.php(1155): OC_Image->resizeNew(256)
#3 /var/www/html/lib/private/Preview/Generator.php(430): OC_Image->resizeCopy(256)
#4 /var/www/html/lib/private/Preview/Generator.php(186): OC\Preview\Generator->generatePreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OCP\Image), 256, 0, false, 849, 1, '')
#5 /var/www/html/lib/private/PreviewManager.php(204): OC\Preview\Generator->generatePreviews(Object(OC\Files\Node\File), Array, 'image/gif')
```
