### ISSUE TITLE
An unhandled exception has been thrown

### ISSUE THREAD

**Issue by rarealphacat** [nextcloud/previewgenerator#280]
An unhandled exception has been thrown:
ValueError: Invalid or uninitialized Zip object in /var/www/html/nextcloud/lib/private/Archive/ZIP.php:154
Stack trace:
#0 /var/www/html/nextcloud/lib/private/Archive/ZIP.php(154): ZipArchive->getStream()
#1 /var/www/html/nextcloud/lib/private/Preview/Bundled.php(42): OC\Archive\ZIP->extractFile()
#2 /var/www/html/nextcloud/lib/private/Preview/OpenDocument.php(44): OC\Preview\Bundled->extractThumbnail()
#3 /var/www/html/nextcloud/lib/private/Preview/GeneratorHelper.php(62): OC\Preview\OpenDocument->getThumbnail()
#4 /var/www/html/nextcloud/lib/private/Preview/Generator.php(245): OC\Preview\GeneratorHelper->getThumbnail()
#5 /var/www/html/nextcloud/lib/private/Preview/Generator.php(140): OC\Preview\Generator->getMaxPreview()
#6 /var/www/html/nextcloud/lib/private/PreviewManager.php(204): OC\Preview\Generator->generatePreviews()
#7 /var/www/html/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(217): OC\PreviewManager->generatePreviews()
#8 /var/www/html/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(195): OCA\PreviewGenerator\Command\PreGenerate->processFile()
#9 /var/www/html/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(163): OCA\PreviewGenerator\Command\PreGenerate->processRow()
#10 /var/www/html/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(131): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#11 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\PreGenerate->execute()
#12 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#13 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#14 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#15 /var/www/html/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#16 /var/www/html/nextcloud/console.php(99): OC\Console\Application->run()
#17 /var/www/html/nextcloud/occ(11): require_once('...')

Anyone having the same?
Nextcloud 22.2.3
Linux 5.4.0

**Comment by rarealphacat** [comment]
solved by restarting
