### ISSUE TITLE
PreviewGenerator failed when processing files on the $path argument

### ISSUE THREAD

**Issue by vinnydancervv** [nextcloud/previewgenerator#322]
Here is the error a get when running this on a specific user that sync long file path, is it related or can it be something else ?

What i tried and check as of yet :
- Every other user is functioning well
- I retried without the office related providers, only excel files are include in the folder that trigger the error, and it failed on the same file.
- I updated to the last version of PreviewGenerator and Nextcloud, no difference.
Nextcloud server version: 25.0.1.1      PreviewGenerator version : 5.1.1
- There is nothing in syslog relating this error, is there a verbose parameter somewhere i can activate?

```
2022-11-09T00:48:39+00:00 Generating previews for /Estimation/files/Compta-General/9. Fichiers Comptabilité/Remboursement Dépenses & Kilométrage/2019/2019 Élodie Dépenses Kilométrage et Achat.xlsx
2022-11-09T00:48:39+00:00 Generating previews for /Estimation/files/Compta-General/9. Fichiers Comptabilité/Remboursement Dépenses & Kilométrage/2019/2019.Remboursement.Kilométrage.Cynthia.xlsx
2022-11-09T00:48:39+00:00 Generating previews for /Estimation/files/Compta-General/9. Fichiers Comptabilité/Remboursement Dépenses & Kilométrage/2019/2019.Remboursement.Kilométrage.vLens.xlsx
An unhandled exception has been thrown:
TypeError: OC\Files\Utils\PathHelper::normalizePath(): Argument #1 ($path) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/Node/Node.php on line 311 and defined in /var/www/nextcloud/lib/private/Files/Utils/PathHelper.php:52
Stack trace:
#0 /var/www/nextcloud/lib/private/Files/Node/Node.php(311): OC\Files\Utils\PathHelper::normalizePath()
#1 /var/www/nextcloud/lib/private/Files/Node/Folder.php(72): OC\Files\Node\Node->normalizePath()
#2 /var/www/nextcloud/lib/private/Files/Node/Folder.php(138): OC\Files\Node\Folder->getFullPath()
#3 /var/www/nextcloud/apps/onlyoffice/lib/preview.php(364): OC\Files\Node\Folder->get()
#4 /var/www/nextcloud/apps/onlyoffice/lib/preview.php(261): OCA\Onlyoffice\Preview->getFileParam()
#5 /var/www/nextcloud/lib/private/Preview/ProviderV1Adapter.php(53): OCA\Onlyoffice\Preview->getThumbnail()
#6 /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php(65): OC\Preview\ProviderV1Adapter->getThumbnail()
#7 /var/www/nextcloud/lib/private/Preview/Generator.php(343): OC\Preview\GeneratorHelper->getThumbnail()
#8 /var/www/nextcloud/lib/private/Preview/Generator.php(162): OC\Preview\Generator->getMaxPreview()
#9 /var/www/nextcloud/lib/private/PreviewManager.php(200): OC\Preview\Generator->generatePreviews()
#10 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(234): OC\PreviewManager->generatePreviews()
#11 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(216): OCA\PreviewGenerator\Command\Generate->parseFile()
#12 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFolder()
#13 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFolder()
#14 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFolder()
#15 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFolder()
#16 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(194): OCA\PreviewGenerator\Command\Generate->parseFolder()
#17 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(146): OCA\PreviewGenerator\Command\Generate->generateUserPreviews()
#18 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute()
#19 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#20 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#21 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#22 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#23 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#24 /var/www/nextcloud/occ(11): require_once('...')
```

**Comment by lmgarret** [comment]
I had the same issue, the bug seems to be with onlyoffice: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/717.
A temporary workaround is to manually edit `apps/onlyoffice/lib/feilversions.php` to include the fix suggested https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/718

**Comment by st3iny** [comment]
That makes sense. The failing path contains `.v`. It seems that the upstream bug has been fixed in https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/1b5759ce62d1cfe59906b10737c45cb80081f80a and is pending for release.

I'm closing the issue as there is nothing else to do but to wait for the next release of onlyoffice-nextcloud.
