### ISSUE TITLE
ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by valdearg** [nextcloud/previewgenerator#353]
Tried running with a path: `sudo -u www-data php7.4 /var/www/nextcloud/occ preview:generate-all --path="/valdearg/files/Photos/Gallery-DL" --verbose`

Gave me the following error, doesn't seem to matter the path:

```
An unhandled exception has been thrown:
ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php:51
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 [internal function]: spl_autoload_call()
#3 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): ReflectionClass->__construct()
#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#6 /var/www/nextcloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /var/www/nextcloud/lib/private/Console/Application.php(219): OC\ServerContainer->query()
#8 /var/www/nextcloud/lib/private/Console/Application.php(130): OC\Console\Application->loadCommandsFromInfoXml()
#9 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands()
#10 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#11 {main}%                                                                  
```

Removed the |null at: https://github.com/nextcloud/previewgenerator/blob/main/lib/Command/Generate.php#L51

Seemed to get rid of the error, not sure if that's correct or I'm missing something.

**Comment by st3iny** [comment]
Which version of Previewgenerator are you running? The latest version is not compatible with PHP 7.4 anymore.

**Comment by valdearg** [comment]
Bah, I run the website using 8.0.27 and was running the command using the 7.4. 

Works fine using the 8.0/8.1, apologies for raising a daft issue!
