### ISSUE TITLE
TypeError: OC_Image::getOrientation(): Return value must be of type int, array returned

### ISSUE THREAD

**Issue by frnmst** [nextcloud/previewgenerator#452]
Hello,

I'm running Nextcloud 26.0.11 and previewgenerator 5.4.0.

I am in the process of regenerating the image previews. Unfortunately I get this error:

```
TypeError: OC_Image::getOrientation(): Return value must be of type int, array returned in /var/www/html/lib/private/legacy/OC_Image.php:460
Stack trace:
#0 /var/www/html/lib/private/legacy/OC_Image.php(494): OC_Image->getOrientation()
#1 /var/www/html/lib/private/Preview/Image.php(52): OC_Image->fixOrientation()
#2 /var/www/html/lib/private/Preview/GeneratorHelper.php(64): OC\Preview\Image->getThumbnail(Object(OC\Files\Node\File), 800, 800)
#3 /var/www/html/lib/private/Preview/Generator.php(440): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\JPEG), Object(OC\Files\Node\File), 800, 800)
#4 /var/www/html/lib/private/Preview/Generator.php(164): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'image/jpeg', '')
#5 /var/www/html/lib/private/PreviewManager.php(212): OC\Preview\Generator->generatePreviews(Object(OC\Files\Node\File), Array, 'image/jpeg')
#6 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(230): OC\PreviewManager->generatePreviews(Object(OC\Files\Node\File), Array)
#7 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFile(Object(OC\Files\Node\File))
#8 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(181): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#9 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(129): OCA\PreviewGenerator\Command\Generate->generatePathPreviews(Object(OC\User\User), '/fmasotti/files...')
#10 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\Generate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/console.php(100): OC\Console\Application->run()
#16 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

As a temporary solution I modified the source code (`/var/www/html/lib/private/legacy/OC_Image.php`) like this:

```diff
public function getOrientation(): int {

    // rest of the function

    $this->exif = $exif;
+   if (gettype($exif['Orientation']) == 'array') {
+       return -1;
+   }
    return $exif['Orientation'];
}
```

By returning -1, when an array is detected, the program continues its job. I can't do many experiments since this is a production environment.

**Comment by joshtrichards** [comment]
That's really weird. 

Per PHP `$exif['Orientation']` shouldn't itself be an array ever. 

I'd be really interested in what *is* in `$exif['Orientation']` in your case.

Do you happen to have a shareable image that triggers this behavior?

Also, what specific version of PHP and OS distribution?

**Comment by frnmst** [comment]
I'm running it again because I can't find the text file dump I made so I don't remember the exact file name. Can the error be triggered again without a full regeneration, like this?

```
docker-compose exec -T --user www-data app php occ preview:generate-all
```

I'm running Nextcloud 26.0.13, Docker version, not the AIO. It was 26.0.12 at the time I opened this issue.

**Comment by jschanz** [comment]
I have the same problem and requested a list of the "defective" images. In all cases, the "Orientation" property does not contain an integer but some form of garbage data. I solved the problem for myself with the following workaround. The function should check if the "Orientation" property contains an officially valid value (1-8).

```php
                $this->exif = $exif;
                if (isset($exif['Orientation']) && is_int($exif['Orientation'])) {
                        return $exif['Orientation'];
                } else {
                        return -1;
                }
```

![2024-06-11_20-16](https://github.com/nextcloud/previewgenerator/assets/5750462/b9111e9d-3173-4e3f-9e93-84649dc65acb)

**Comment by frnmst** [comment]
> I have the same problem and requested a list of the "defective" images. In all cases, the "Orientation" property does not contain an integer but some form of garbage data. I solved the problem for myself with the following workaround. The function should check if the "Orientation" property contains an officially valid value (1-8).
> 
> ```
>                 $this->exif = $exif;
>                 if (isset($exif['Orientation']) && is_int($exif['Orientation'])) {
>                         return $exif['Orientation'];
>                 } else {
>                         return -1;
>                 }
> ```
> 
> ![2024-06-11_20-16](https://private-user-images.githubusercontent.com/5750462/338702840-b9111e9d-3173-4e3f-9e93-84649dc65acb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNDI3MjUsIm5iZiI6MTcxODE0MjQyNSwicGF0aCI6Ii81NzUwNDYyLzMzODcwMjg0MC1iOTExMWU5ZC0zMTczLTRlM2YtOWU5My04NDY0OWRjNjVhY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMjE0NzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGNmYzY3ZDAxNTczYjM0M2U1MTJmODRiNWEyNDFjYTQ2MDY5ZGYzYjljNWMyODUxMGVkMThiMzc2ZWUyNzk3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eAa5q1afMgZWYyXPQ8VeaWzqDGSvs0_0YuW1_N0wd9M)

Very interesting. I will certainly patch my instance if I happen to do a full re-scan again!
