### ISSUE TITLE
PathHelper error when trying to generate for a specific folder

### ISSUE THREAD

**Issue by thegrasshopper104** [nextcloud/previewgenerator#455]
I'm running the Nextcloud snap, `27.1.6.` 
I don't get any previews for really large photos, so I increased the size limit and memory limit.
I then tried to regenerate thumbnails for the folder these large photos are stored in, and got this:
```
sudo nextcloud.occ preview:generate-all --path="/user/Photos/subfolder"
An unhandled exception has been thrown:
TypeError: OC\Files\Utils\PathHelper::normalizePath(): Argument #1 ($path) must be of type string, null given, called in /snap/nextcloud/40228/htdocs/lib/private/Files/Node/Node.php on line 319 and defined in /snap/nextcloud/40228/htdocs/lib/private/Files/Utils/PathHelper.php:52
Stack trace:
#0 /snap/nextcloud/40228/htdocs/lib/private/Files/Node/Node.php(319): OC\Files\Utils\PathHelper::normalizePath()
#1 /snap/nextcloud/40228/htdocs/lib/private/Files/Node/Folder.php(70): OC\Files\Node\Node->normalizePath()
#2 /snap/nextcloud/40228/htdocs/lib/private/Files/Node/Folder.php(135): OC\Files\Node\Folder->getFullPath()
#3 /var/snap/nextcloud/40228/nextcloud/extra-apps/previewgenerator/lib/Command/Generate.php(179): OC\Files\Node\Folder->get()
#4 /var/snap/nextcloud/40228/nextcloud/extra-apps/previewgenerator/lib/Command/Generate.php(129): OCA\PreviewGenerator\Command\Generate->generatePathPreviews()
#5 /snap/nextcloud/40228/htdocs/3rdparty/symfony/console/Command/Command.php(298): OCA\PreviewGenerator\Command\Generate->execute()
#6 /snap/nextcloud/40228/htdocs/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#7 /snap/nextcloud/40228/htdocs/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#8 /snap/nextcloud/40228/htdocs/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#9 /snap/nextcloud/40228/htdocs/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#10 /snap/nextcloud/40228/htdocs/console.php(100): OC\Console\Application->run()
#11 /snap/nextcloud/40228/htdocs/occ(11): require_once('...')
#12 {main}
```

**Comment by avatar1024** [comment]
I also hit this. Any idea what it might be?

**Comment by joshtrichards** [comment]
Yes, add `files` path as described in the help output for that command as well as here:

https://github.com/nextcloud/previewgenerator?tab=readme-ov-file#commands

Hope that helps. Closing since this isn't a bug.
