### ISSUE TITLE
An unhandled exception has been thrown

### ISSUE THREAD

**Issue by mellow2012** [nextcloud/previewgenerator#501]
Hi

we had this problem sometimes:
there are vwx (Vectorworks) and dwg (Autocad) files in the folder

Error:
`An unhandled exception has been thrown:
ValueError: Path cannot be empty in /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/richdocuments/lib/Preview/Office.php:65
Stack trace:
#0 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/richdocuments/lib/Preview/Office.php(65): fopen()
#1 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/Preview/GeneratorHelper.php(64): OCA\Richdocuments\Preview\Office->getThumbnail()
#2 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/Preview/Generator.php(361): OC\Preview\GeneratorHelper->getThumbnail()
#3 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/Preview/Generator.php(337): OC\Preview\Generator->generateProviderPreview()
#4 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/Preview/Generator.php(143): OC\Preview\Generator->getMaxPreview()
#5 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/PreviewManager.php(211): OC\Preview\Generator->generatePreviews()
#6 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(232): OC\PreviewManager->generatePreviews()
#7 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFile()
#8 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#9 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#10 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#11 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#12 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(183): OCA\PreviewGenerator\Command\Generate->parseFolder()
#13 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(131): OCA\PreviewGenerator\Command\Generate->generatePathPreviews()
#14 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\PreviewGenerator\Command\Generate->execute()
#15 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#16 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#17 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#18 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#19 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/console.php(102): OC\Console\Application->run()
#20 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/occ(11): require_once('...')
`

**Comment by mellow2012** [comment]
I have found the reason why this error occurs
If the file is no longer in SMB storage but is still present in oc_filecache, then this problem occurs
