### ISSUE TITLE
TypeError is thrown in preview generator

### ISSUE THREAD

**Issue by nielstron** [nextcloud/previewgenerator#510]
```
2024-09-09T20:48:53+00:00 Scanning folder /anonymized/path
An unhandled exception has been thrown:
TypeError: stream_get_contents(): Argument #1 ($stream) must be of type resource, false given in /var/www/html/lib/private/Preview/ProviderV2.php:93
Stack trace:
#0 /var/www/html/lib/private/Preview/ProviderV2.php(93): stream_get_contents()
#1 /var/www/html/lib/private/Preview/Movie.php(99): OC\Preview\ProviderV2->getLocalFile()
#2 /var/www/html/lib/private/Preview/GeneratorHelper.php(64): OC\Preview\Movie->getThumbnail()
#3 /var/www/html/lib/private/Preview/Generator.php(361): OC\Preview\GeneratorHelper->getThumbnail()
#4 /var/www/html/lib/private/Preview/Generator.php(337): OC\Preview\Generator->generateProviderPreview()
#5 /var/www/html/lib/private/Preview/Generator.php(143): OC\Preview\Generator->getMaxPreview()
#6 /var/www/html/lib/private/PreviewManager.php(211): OC\Preview\Generator->generatePreviews()
#7 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(232): OC\PreviewManager->generatePreviews()
#8 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFile()
#9 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#10 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#11 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#12 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#13 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#14 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(192): OCA\PreviewGenerator\Command\Generate->parseFolder()
#15 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(138): OCA\PreviewGenerator\Command\Generate->generateUserPreviews()
#16 /var/www/html/lib/private/User/Manager.php(666): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}()
#17 /var/www/html/apps/previewgenerator/lib/Command/Generate.php(137): OC\User\Manager->callForSeenUsers()
#18 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\PreviewGenerator\Command\Generate->execute()
#19 /var/www/html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#20 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#21 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#22 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#23 /var/www/html/console.php(102): OC\Console\Application->run()
#24 /var/www/html/occ(11): require_once('...')
```
Already occured several times, trying to generate previews for all files.

Nextcloud: [Nextcloud Hub 8](https://nextcloud.com/) (29.0.6)
Preview generator: 5.6.0

**Comment by st3iny** [comment]
I think I found the problematic piece of code.

@nielstron Could you please share some more information on the problematic file?

1. Does the error occur on the same file over and over again?
2. Is the file on local storage, S3 primary storage or an external storage?

**Comment by nielstron** [comment]
1. The error occurs sporadically, on different files
2. The file is on external storage (SFTP)
3. I can not check this point because this file belongs to a user. Its very possible that the file is corrupted

**Comment by st3iny** [comment]
Ok, thanks for the info.

So it seems that the underlying issue is probably caused by a flaky connection to the SFTP server. Hence the call to `fopen` fails.

I'll create a PR to handle this case gracefully.
